### ISSUE TITLE
hmr giving an error on not-symmetric CpGs but hmr-rep working fine

### ISSUE THREAD

**Issue by moqri** [smithlabcode/dnmtools#116]
**Describe the bug**
We are using a data CpG count data which is converted from another pipeline (so missing some CpGS) but overall symmetric.
running hmr gives an error but hmr-rep works fine

**To Reproduce**
source: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM5663172
"beta" file is converted to bed file and lifted to hg38. the file is reformatted and sorted to match meth-count. then running hmr on this data will result in "error: input is not symmetric-CpGs"

However, running hmr-rep with two identical copies of the processed data works fine!

**Expected behavior**
not clear if all (symmetric) CpGs are required for hmr to work or if there is another issue (e.g. two consecutive CpG coordinate?). not clear why hmr-rep works but hmr doesn't

Thanks for the great work!

**Comment by andrewdavidsmith** [comment]
@moqri We will test this to determine if the behavior is as it should be. Clearly a change needs to be made in one direction or the other.

**Comment by andrewdavidsmith** [comment]
@moqri I'm going to close this and merge this into issue #43 and copy your comments from this issue.
