### ISSUE TITLE
Calling HMRs on the DNA Methylation Atlas Data

### ISSUE THREAD

**Issue by moqri** [smithlabcode/dnmtools#129]
**Describe the bug**
It seems the HMR function doesn't work as expected on the DNA Methylation Atlas Data (calling methylated regions as HMRs). 

**To Reproduce**
1. Download a Beta file from their GEO repository (e.g. https://ftp.ncbi.nlm.nih.gov/geo/samples/GSM5652nnn/GSM5652279/suppl/GSM5652279%5FBlood%2DT%2DCD4%2DZ000000TT%2Ehg38%2Ebeta) 

2. Convert Beta file to DNAMTolls "count format. I am (temporarily) putting my converted count file here, in case you can check and see if there is anything wrong with the data:
https://storage.googleapis.com/hmr_reference/SM5652293_Blood-T-EffMem-CD4.meth.gz
This is how my reformatted data look: 
![image](https://github.com/smithlabcode/dnmtools/assets/4342458/dcb14e72-0193-4b0b-8a48-92c44e9c97ca)

3. Call DNAMTools HMR. This is what I get
![image](https://github.com/smithlabcode/dnmtools/assets/4342458/77b74a15-60fb-4bc0-a536-8faf4d4753d8)

4. checking one of the larger HMRs in their USCS track (http://genome-euro.ucsc.edu/s/tomkap/Atlas_hg38). this is what I get which seems mostly methylated (this seems to be the case for many other called HMRs) 
![image](https://github.com/smithlabcode/dnmtools/assets/4342458/a33e20b6-394b-428b-a5c7-047a19167abb)

I am (temporarily) putting my converted count file here, in case you can check and see if there is anything wrong with the data:
https://storage.googleapis.com/hmr_reference/SM5652293_Blood-T-EffMem-CD4.meth.gz

**Comment by andrewdavidsmith** [comment]
@moqri I'm not sure I understand the problem. I see your image. I don't immediately see any problems with the counts format file you made, and I might be missing it, but I don't see the problem with the HMRs. I can't compare using those 10 lines, but I ran `hmr` on the file you posted, and it seemed reasonable. I'll check closer, but if you can tell me specifically what looks wrong in yoru `.3` image of HMR output, it would help.

**Comment by andrewdavidsmith** [comment]
I downloaded your file, ran `hmr` on it, then computed the weighted mean methylation in each of the resulting HMRs. I get the following:
```
0     0.05  6847
0.05  0.1   12012
0.1   0.15  8102
0.15  0.2   6066
0.2   0.25  4699
0.25  0.3   4369
0.3   0.35  4627
0.35  0.4   4606
0.4   0.45  1580
0.45  0.5   58
0.5   0.55  2
0.55  0.6   1
0.6   0.65  1
0.65  0.7   0
0.7   0.75  0
0.75  0.8   0
0.8   0.85  0
0.85  0.9   0
0.9   0.95  0
0.95  1     0
```
I would guess that a different averaging would skew lower, but overall this suggests things are working. I will look at the larger ones to see if there's something going on with those. Keep in mind that the genome browser can be easy to misinterpret visually depending on coverage and CpG density.

**Comment by moqri** [comment]
Thank you @andrewdavidsmith, very helpful!

It seems the problem is with their data. Possibly mislabeling hg19 as hg38. I will look deeper into their data and will update here. 

 the weighted mean approach for checking is indeed more reliable. Can you please post which command you are using to get it. 

I also compared the HMR and meth

**Comment by moqri** [comment]
Indeed it was the hg19 vs hg38 issue!
Apparently wgbstools beta2bed convert to hg19 by default (even if the beta files are hg38!). 
https://github.com/nloyfer/wgbs_tools

@andrewdavidsmith please feel free to close this issue. I might open another issue about a small portion of HMRs that could be potentially enhanced (or post processed/filtered) if it is fine with you.
