### ISSUE TITLE
Segmentation fault (core dumped) while using bsrate 

### ISSUE THREAD

**Issue by Akshaygala** [smithlabcode/dnmtools#14]
I am trying to use bsrate function and am getting segmentation fault error. Here is the glimpse of my code:
"
INbam="${!SGE_TASK_ID}"
samtools view -H "${INbam/.bam/}".sam > "${INbam/.bam/}".headers.txt                                                    && \
awk -F "\t" '{if ($3=="MT") print}' "${INbam/.bam/}".sam > "${INbam/.bam/}".reads.sam                          && \
cat "${INbam/.bam/}".headers.txt "${INbam/.bam/}".reads.sam > "${INbam/.bam/}".chrMT.sam               && \
rm "${INbam/.bam/}".headers.txt "${INbam/.bam/}".reads.sam                                                                      && \

bsrate -c "${INbam/.bam/}".chrMT.sam -o "${INbam/.bam/}".bsrate "${INbam/.bam/}".sam
"

I am providing the bam files using an array job. My chrMT.sam files have headers text followed by the MT reads. I have attached my input file for bsrate. Any help will be appreciated. 
[S9_.bsbolt-grch38.sorted.deduped.chrMT.txt](https://github.com/smithlabcode/methpipe/files/7937688/S9_.bsbolt-grch38.sorted.deduped.chrMT.txt)

Thanks.

Akshay

**Comment by andrewdavidsmith** [comment]
I'm closing this issue because the code for bsrate has changed enough that if any segfaults are happening now, they would likely have a different cause.
