### ISSUE TITLE
A question for 'dnmtools allelic'

### ISSUE THREAD

**Issue by ETC100** [smithlabcode/dnmtools#168]
Hello, I recently have a study on allelic-specific methylation. However, I'm not really understand the output of 'dnmtools allelic' function.
The output contained four columns, methylated methylated (mm), methylated unmethylated (mu), unmethylated methylated (um) and unmethylated unmethylated (uu), but I want to know these allelic-specific methylation are paternal biased or maternal biased. For instance, gatk toolkit will give you the allelic read count numbers for reference and alternative according to SNP data, and then we can clarified the paternal/maternal bias.

**Comment by andrewdavidsmith** [comment]
@ETC100 allelic is for visualization. If you use the various tools for ASM in dnmtools and find regions of ASM, the quickest way I can think of to determine if they are maternal or paternally methylated is to compare with a sperm methylome. I think the `amrfinder` tool was updated in the most recent release and should be updated on conda soon.

**Comment by andrewdavidsmith** [comment]
Closing this issue as it's a question about the underlying biology.
