### ISSUE TITLE
dnmtools hmr_rep: what is the "CONVERGED" for replicate methylomes.

### ISSUE THREAD

**Issue by owwap** [smithlabcode/dnmtools#30]
Hi Guilherme,

Many thanks for the nice tool dnmtools! Would you kind please help to solve a problem when running the command dnmtools hmr_rep. when there are 2 or 3 replicate sets, the results showed as the following:
[separating by cpg desert]
[cpgs retained: 28091984]
[deserts removed: 103730]
ITR  F size  B size      F PARAMS      B PARAMS      DELTA
  1    3.71   21.13   0.544 2.033   5.770 0.963   1.00e+00
  2    6.29   35.22   0.519 1.768   5.695 0.956   4.88e-01
  3    8.21   45.26   0.513 1.670   5.683 0.954   2.59e-03
  4    9.27   50.67   0.511 1.626   5.677 0.952   4.14e-04
  5    9.77   53.20   0.510 1.606   5.673 0.952   4.97e-05
  6    9.99   54.30   0.509 1.597   5.672 0.951   2.09e-06
  7   10.09   54.76   0.509 1.592   5.672 0.951   4.60e-06
  8   10.13   54.95   0.509 1.590   5.672 0.951   2.17e-06
  9   10.14   55.01   0.509 1.589   5.673 0.951   5.92e-07
 10   10.15   55.04   0.509 1.588   5.673 0.951   1.04e-07
 
When there are 4 replicate sets, the results showed as the following:
 [separating by cpg desert]
[cpgs retained: 27883296]
[deserts removed: 105941]
ITR  F size  B size      F PARAMS      B PARAMS      DELTA
  1    3.36   19.36   0.518 1.774   5.348 0.920   1.00e+00
  2    4.69   26.45   0.508 1.651   5.509 0.935   4.53e-01
  3    5.23   28.94   0.508 1.598   5.586 0.940   7.30e-04
  4    5.41   29.50   0.508 1.568   5.639 0.943   1.04e-04
  5    5.45   29.41   0.509 1.548   5.681 0.946   5.04e-05
  6    5.45   29.14   0.510 1.534   5.715 0.948   4.10e-05
CONVERGED

And when there are 5 replicate sets, the results showed as the following:
[separating by cpg desert]
[cpgs retained: 27675526]
[deserts removed: 107588]
ITR  F size  B size      F PARAMS      B PARAMS      DELTA
  1    3.07   16.15   0.523 1.477   5.558 0.927   1.00e+00
  2    3.95   19.62   0.519 1.342   5.803 0.945   4.45e-01
  3    4.19   19.89   0.524 1.281   5.980 0.955   7.84e-04
  4    4.24   19.34   0.530 1.244   6.127 0.964   2.97e-04
  5    4.22   18.70   0.535 1.217   6.250 0.970   2.20e-04
CONVERGED

I wonder if this is normal？ and what is the "CONVERGED" for replicate methylomes? Thanks!

With my best.

**Comment by owwap** [comment]
Furthermore, the option -partial doesn't work.

**Comment by andrewdavidsmith** [comment]
@owwap Thanks for these questions.

Regarding the `CONVERGED` at present this is determined by no change in the state transition parameter value estimates. In particular, if the relative change to these estimates is below 1e-10, then we declare convergence. This means we no longer need to do any more iterations. This is quite strict criteria, so it's fine if you don't observe this convergence in some of your runs. I should document this. Thanks for pointing it out.

Regarding the `-partial` option. It is not actually included for `hmr-rep`. It is incorrectly indicated in the documentation, which I will update right away.
