### ISSUE TITLE
CpGx

### ISSUE THREAD

**Issue by idkimnew2** [smithlabcode/dnmtools#36]
Hello,

for methylation outputs, what is "CpGx" as a methylation site category?

Thank you.

**Comment by andrewdavidsmith** [comment]
@idkimnew2 The `x` indicates that there's evidence that site might be mutated in the sequenced sample, compared with the reference genome. The CpG exists in the reference, but the combined information from both strands in the bisulfite sequencing would indicate that the TpG is not an indication of lack of methylation, but instead an indication of mutation at the site. It appears we need to clarify that in the documentation, so thanks for this question.

**Comment by andrewdavidsmith** [comment]
@idkimnew2 I updated the documentation for the `counts` tool to explain the `x`. I'll close this issue and if you need anything else please open another one.
