### ISSUE TITLE
What constitutes "neighboring" CpG in radmerge

### ISSUE THREAD

**Issue by cstill3928** [smithlabcode/dnmtools#37]
Hi, thanks for the great package, I had a quick question. In the radmerge function what constitutes a neighboring CpG? How far apart do significant CpGs need to be to be considered a part of a separate DMR?

**Comment by andrewdavidsmith** [comment]
@cstill3928 It looks like it's merging as long as they remain significant and are consecutive along the chromosome, regardless of the number of nucleotides in between. It should not merge if sites are on separate chromosomes.

**Comment by andrewdavidsmith** [comment]
@cstill3928 I updated the documentation to explain your question so I'm closing this issue. If you have another question, feel free to open another issue.
