### ISSUE TITLE
Sensivity to CG level relationship in simulation data

### ISSUE THREAD

**Issue by ashraf123456789** [smithlabcode/dnmtools#39]
Hello, 
I compared abismal and bismark performance on simulation data, the data was simulated by MethylFastq. I simulated samples with 10%,50%,90% CG. What I found was that sensitivity was highest at 10% for all different bin sizes. Is this counter intuitive that samples with the highest CG levels had highest amount False Negatives?

Thank you!

**Comment by andrewdavidsmith** [comment]
@ashraf123456789 I think your question can only be answered by someone with detailed knowledge of both MethylFastq and abismal, but I'm not sure any such person exists.
