### ISSUE TITLE
selectsites only works as expected when chroms are lexicographically sorted

### ISSUE THREAD

**Issue by guilhermesena1** [smithlabcode/dnmtools#4]
If the methcounts file and the BED file have consistent chrom order, `selectsites` fast-forwards the BED file, skipping chromosomes that are lexicographically inferior to the next chrom in the methcounts file. We need to steer away from requiring `LC_ALL=C` lexicographic ordering, as it is very rarely how FASTA files order their chromosomes.

**Comment by andrewdavidsmith** [comment]
This behavior needs to be divided according to whether the files are being searched on disk with binary search within the file, or the entire file is loaded into memory. In the latter case, we can make the suggested change. In the former case, we need the order to be consistent so we can do the binary search on disk.

**Comment by andrewdavidsmith** [comment]
Fixed to the extent it can be with commit 28cf73ff653efda6af55fd95cdc3118b3894ca5d
