### ISSUE TITLE
Replace C style heap allocation with stl containers

### ISSUE THREAD

**Issue by andrewdavidsmith** [smithlabcode/dnmtools#55]
This is the wise choice and was forgotten after I worked with C code for several days. After noticing some memory leaks, I realized a character array from the heap should be `vector<char> v` and accessed with `&v[0]`. This should impact `format-reads.cpp` and `uniq.cpp`. Possibly `methcounts.cpp`.

**Comment by masarunakajima** [comment]
All C style heap allocations are now in `src/common/bam_record_utils.cpp`, where they are needed to to `htslib`.
