### ISSUE TITLE
Question with design matrix for radmeth regression and dmr output 

### ISSUE THREAD

**Issue by vagan21** [smithlabcode/dnmtools#76]
Hello. I previously posted about a question surrounding how to create the design matrix under the 'issues' page for methpipe, which is now archived, when you want to account for biological variation between replicates within each group. I understand radmeth regression is set up to this but I am confused on the design matrix format. I am running radmeth regression, followed by radmeth adjust and then radmeth merge to call dmrs. My factor of interest is "is_b1" and is the factor with respect to which I want to test for differential methylation. Within each of the two groups, we have replicates from male and female mice. Ultimately, I want to remove any effects due to sex of the replicates and call dmrs between groups that are genotype-dependent. Do I need to have other columns, besides my factor of interest, which signify my covariates in my design matrix? Interestingly, I already tested out what the dmr output would look like if I ran radmeth regression with different design matrices and this is what I got. See below. If you look at the third and last design matrix, you'll see that I don't have a 'base' column and just 'is_b1' and 'is_F', and its count is so different from the above two, with over 1 million DMRs called. The only different between the third matrix and the first two is that the first two have a 'base' column. I can't explain why the dmr counts are so different. We went from a dmr count in the tens to millions when there isn't a 'base' column and just 'is_b1' and 'is_F'. I also want to add I am using the default parameters for radmeth adjust and radmeth merge. To conclude, I am just trying to figure out the right way to design my matrix and call dmrs based on my factor of interest, is_b1, and accounting for covariates, which in this case is sex. Thanks and any help is appreciated. 
![Screen Shot 2023-07-24 at 5 19 50 PM](https://github.com/smithlabcode/dnmtools/assets/75225141/2a6b8731-c0d6-411f-9169-31c9861c8a7b)

**Comment by andrewdavidsmith** [comment]
@vagan21 Thanks. Just to confirm, you have two variables, one is of interest, and the other you want to control. And you have 8 total methylomes, so 2 replicates for each of your 4(=2x2) factor levels? Do you know if these methylomes have much variation in the global methylation levels?

**Comment by vagan21** [comment]
Correct. My factor of interest is "is_b1" and the other that I want to control is sex ("is_F"). Like you said, there are 4 factor levels: B1F, B1M, B2F, and B2M. Using the tool deepTools, we can compute mean methylation levels at HMRs called across all 8 samples (using the hmr program with MethPipe) and plot the results as a PCA. You can see our samples largely cluster by sex. I've also included the results as a pearson heatmap. There appears some variation between male and female samples.
![Screen Shot 2023-07-25 at 3 17 05 PM](https://github.com/smithlabcode/dnmtools/assets/75225141/c531525e-b696-462f-9991-1f97216de6fe)
![Screen Shot 2023-07-25 at 3 22 13 PM](https://github.com/smithlabcode/dnmtools/assets/75225141/226b5eb7-6db9-41fb-a1e4-4c2f10e35aed)

**Comment by andrewdavidsmith** [comment]
In the radmeth documentation I added an explanation of how to think about your design, which is a very common one, in the context of radmeth. The intercept column is important (labeled "base" in the documentation). If you follow through this updated documentation, you will see what the analysis looks like for a simple example structured like yours, but that's been created to have differences between the two levels for both factors. The important thing to notice is that without the intercept, the potentially confounding factor is not controlled. I hope this helps. I will try to upload the simulated data I used so that you can follow through the individual steps if you want to confirm that you are getting the same output.

**Comment by andrewdavidsmith** [comment]
You can find all the data I used in that "tutorial" on radmeth [here](https://github.com/andrewdavidsmith/radmeth-demo-simulated-data). I will probably compress those files so they are easier to download, but other than that they should remain available.

**Comment by vagan21** [comment]
Thank you for the radmeth tutorial and thorough explanation of how to work with confounding factors. All of this was very helpful!

**Comment by andrewdavidsmith** [comment]
I think the question was very reasonable and a good opportunity for me to set up some test data so people can explore a bit on their own. I will close this issue. Hopefully we will have a new release in a matter of days, including on conda. If you have another question or concern please open another issue.
